"""Interactive first-run setup.

Run this once after extracting the bot. It collects credentials, generates
random secrets for the admin dashboard and writes a ``.env`` file in the
current directory. Re-running it on an existing ``.env`` will offer to
keep, overwrite, or back up the old one.

Usage (the wrappers do this for you):
    python setup.py

Designed to be runnable on a bare Python 3.11+ install \u2014 no third-party
dependencies, just the standard library.
"""
from __future__ import annotations

import re
import secrets
import shutil
import sys
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
ENV_PATH = PROJECT_ROOT / ".env"

BOT_TOKEN_RE = re.compile(r"^\d{6,}:[A-Za-z0-9_-]{30,}$")
ADMIN_IDS_RE = re.compile(r"^\s*\d+(\s*,\s*\d+)*\s*$")


def _ask(prompt: str, *, default: str = "", validator=None,
         error: str = "Invalid input.") -> str:
    """Prompt the user, retrying until validator() passes."""
    suffix = f" [{default}]" if default else ""
    while True:
        try:
            raw = input(f"{prompt}{suffix}: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nSetup aborted.")
            sys.exit(1)
        value = raw or default
        if validator is None or validator(value):
            return value
        print(f"  ! {error}")


def _ask_yes_no(prompt: str, *, default: bool = True) -> bool:
    suffix = "[Y/n]" if default else "[y/N]"
    while True:
        try:
            raw = input(f"{prompt} {suffix}: ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            print("\nSetup aborted.")
            sys.exit(1)
        if not raw:
            return default
        if raw in ("y", "yes"):
            return True
        if raw in ("n", "no"):
            return False
        print("  ! Please answer y or n.")


def _python_version_ok() -> bool:
    return sys.version_info >= (3, 11)


def _gen_password(length: int = 24) -> str:
    """URL-safe random string for the admin dashboard login."""
    return secrets.token_urlsafe(length)[:length]


def _gen_session_secret() -> str:
    """64-char hex string for signing dashboard session cookies."""
    return secrets.token_hex(32)


def _validate_token(value: str) -> bool:
    return bool(BOT_TOKEN_RE.match(value))


def _validate_admin_ids(value: str) -> bool:
    return bool(ADMIN_IDS_RE.match(value))


def _validate_username(value: str) -> bool:
    if not value:
        return True
    return bool(re.match(r"^[A-Za-z0-9_]{3,32}$", value))


def _validate_optional(_: str) -> bool:
    return True


ENV_TEMPLATE = """\
# ============================================================================
# BABA SWIFT BOT \u2014 environment configuration
# Generated by setup.py on {now}.
# Edit values by hand any time, then restart the bot.
# DO NOT commit this file. (.gitignore already excludes it.)
# ============================================================================

# Telegram bot token from @BotFather
BOT_TOKEN={BOT_TOKEN}

# Comma-separated Telegram user IDs that have admin powers
ADMIN_IDS={ADMIN_IDS}

# Public username of the bot (without @). Leave blank to auto-detect at startup.
BOT_USERNAME={BOT_USERNAME}

# Branding
SHOP_NAME={SHOP_NAME}
SUPPORT_USERNAME={SUPPORT_USERNAME}

# Manual deposit destinations shown to users
BINANCE_UID={BINANCE_UID}
UPI_ID={UPI_ID}
UPI_NAME={UPI_NAME}

# SQLite by default. To switch to Postgres later, use postgresql+asyncpg://...
DATABASE_URL=sqlite+aiosqlite:///./data/bot.db

# Localhost-only admin web dashboard (http://127.0.0.1:8088)
DASHBOARD_HOST=127.0.0.1
DASHBOARD_PORT=8088
DASHBOARD_PASSWORD={DASHBOARD_PASSWORD}
DASHBOARD_SESSION_SECRET={DASHBOARD_SESSION_SECRET}

# Referral economics
REFERRAL_COMMISSION_PCT=2.0
REFERRAL_FIRST_PURCHASE_BONUS_USDT=0.50

# Withdrawal limits (USDT)
WITHDRAW_MIN=5
WITHDRAW_MAX=1000

# Logging: DEBUG / INFO / WARNING / ERROR
LOG_LEVEL=INFO

# Premium custom emojis on inline keyboard buttons (Bot API 9.4).
# Requires the bot owner to hold a Telegram Premium subscription.
# Set to false to fall back to plain unicode glyphs in button text.
PREMIUM_BUTTON_ICONS=true

# Bot API 9.4 button colours (primary / success / danger).
# Set to false for the client's default button colour everywhere.
BUTTON_STYLES_ENABLED=true
"""


def _print_header() -> None:
    print()
    print("=" * 66)
    print(" BABA SWIFT BOT \u2014 first-run setup")
    print("=" * 66)
    print()
    if not _python_version_ok():
        print(f"WARNING: detected Python {sys.version.split()[0]}.")
        print("This bot needs Python 3.11 or newer. Continuing anyway, but the")
        print("bot may fail to start. Install a newer Python from")
        print("https://www.python.org/downloads/ if you hit problems.")
        print()


def _handle_existing_env() -> bool:
    """Returns True if we should proceed and write a new .env."""
    if not ENV_PATH.exists():
        return True
    print("A .env file already exists in this folder.")
    print("  1) Keep it as-is and quit setup")
    print("  2) Back it up to .env.bak and create a fresh one")
    print("  3) Overwrite it without backup")
    while True:
        try:
            choice = input("Choose 1, 2 or 3: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nSetup aborted.")
            sys.exit(1)
        if choice == "1":
            print("Keeping existing .env. Run setup.py again any time to redo.")
            return False
        if choice == "2":
            backup = PROJECT_ROOT / f".env.bak.{datetime.now():%Y%m%d_%H%M%S}"
            shutil.copy2(ENV_PATH, backup)
            print(f"Existing .env backed up to {backup.name}")
            return True
        if choice == "3":
            return True
        print("  ! Please answer 1, 2 or 3.")


def main() -> int:
    _print_header()

    if not _handle_existing_env():
        return 0

    print("Need help finding values? See START_HERE.txt or:")
    print("  - BOT_TOKEN     \u2192 Telegram \u2192 @BotFather \u2192 /newbot")
    print("  - your user ID  \u2192 Telegram \u2192 @userinfobot")
    print()

    bot_token = _ask(
        "BOT_TOKEN (looks like 1234567890:AA...)",
        validator=_validate_token,
        error="Token format should be 'digits:letters_digits_dashes' from BotFather.",
    )
    admin_ids = _ask(
        "Your Telegram user ID(s), comma-separated",
        validator=_validate_admin_ids,
        error="Enter one or more numeric IDs separated by commas.",
    )
    bot_username = _ask(
        "Bot username without @ (blank = auto-detect at startup)",
        default="",
        validator=_validate_username,
        error="Use 3-32 characters: letters, digits, underscore.",
    )
    shop_name = _ask("Shop name shown in headers", default="Baba Swift Shop")
    support_username = _ask(
        "Support Telegram username without @",
        default="babaswiftbot",
        validator=_validate_username,
        error="Use 3-32 characters: letters, digits, underscore.",
    )
    binance_uid = _ask(
        "Binance UID for manual deposits (blank to skip)",
        default="",
        validator=_validate_optional,
    )
    upi_id = _ask(
        "UPI ID for manual deposits (blank to skip)",
        default="",
        validator=_validate_optional,
    )
    upi_name = _ask(
        "Account holder name shown next to the UPI ID",
        default=shop_name,
        validator=_validate_optional,
    )

    dashboard_password = _gen_password()
    session_secret = _gen_session_secret()

    env_text = ENV_TEMPLATE.format(
        now=datetime.now().isoformat(timespec="seconds"),
        BOT_TOKEN=bot_token,
        ADMIN_IDS=admin_ids,
        BOT_USERNAME=bot_username,
        SHOP_NAME=shop_name,
        SUPPORT_USERNAME=support_username,
        BINANCE_UID=binance_uid,
        UPI_ID=upi_id,
        UPI_NAME=upi_name,
        DASHBOARD_PASSWORD=dashboard_password,
        DASHBOARD_SESSION_SECRET=session_secret,
    )
    ENV_PATH.write_text(env_text, encoding="utf-8")

    # Make sure the SQLite folder exists so first launch doesn't crash.
    (PROJECT_ROOT / "data").mkdir(exist_ok=True)

    print()
    print("=" * 66)
    print(" Setup complete.")
    print("=" * 66)
    print(f"  .env written to:        {ENV_PATH}")
    print(f"  Dashboard URL:          http://127.0.0.1:8088")
    print(f"  Dashboard password:     {dashboard_password}")
    print()
    print("  (The password is also stored in .env. Don't share that file.)")
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
